### ISSUE TITLE
Bots not spawning in RSE mod

### ISSUE THREAD

**Issue by win32re** [twizre/iw4lan#1]

**Comment by win32re** [comment]
Fixed in revision 45.

**Comment by Tex-Rec** [comment]
Working nice now on the 45 ! No bugs so far witht he RSE ! I still dont understand why is the NAT Stricted. Are you looking on that too ?

**Comment by win32re** [comment]
@Tex-Rec IWNet/IWNetServer tells the game if your NAT is strict. Since there's no IWNetServer, the game will always say that your NAT is strict.

tl;dr Nothing to worry about, it's just a bug because there's no master server.

**Comment by win32re** [comment]
My mail is win32re@gmail.com

**Comment by Tex-Rec** [comment]
i have imagine something like that , is there a way simply to remove totally this message from there !

**Comment by win32re** [comment]
Yeah, I might change it so it always says NAT is open.
